spring:
  # 数据源
  datasource:
    username: root
    password: cuber@zhang
    url: jdbc:mysql://192.168.136.100:3306/backend-init?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60_000
      connect-timeout: 30_000
      test-while-idle: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          enabled: true

  # 数据库版本控制
  flyway:
    baseline-on-migrate: true
    baseline-version: 20230504001

# mybatis-plus相关
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring-security忽略资源
security:
  ignore:
    urls:
      - /user/login
      - /swagger-ui.html
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs
      - /webjars/**

#日志相关
logging:
  level:
    root: info
  file:
    name: logs/backend.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/backend-%d{yyyy-MM-dd}-%i.log
